site_name: 'InvestContest 2023'
docs_dir: docs
repo_url: https://github.com/InvestContest/2024/
theme:
  name: material
  custom_dir: overrides
  language: 'ru'
  palette:
    primary: black
    accent: yellow
  # custom_dir: swagger-iu/
plugins:
  - search:
      indexing: 'full'
      lang:
        - en
        - ru
      min_search_length: 3
      prebuild_index: false
      separator: "[\\s\\-]+"

nav:
- О конкурсе: 
  - "О конкурсе": index.md
  - "Особенности торговли на тестовом контуре": sandbox.md
- Результаты:
  - "Как считаем доходность": calc.md
  - "Таблица результатов": results.md
  
  